name: neteast up...

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

jobs:
  run_wyy:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: run main.py
      env:
        WYY_UID: ${{secrets.WYY_UID}}
        WYY_PWD: ${{secrets.WYY_PWD}}
        SC_TOKEN: ${{secrets.SC_TOKEN}}
      run: |
        git config --global user.email super_gxq@qq.com
        git config --global user.name xianqiangjun
        python main.py
